[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
timemachine_dapp = "EGVnVqs8pzjUFxjrovN9jsjipUGKh9J2g9vTtBZnaVBV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
